### ISSUE TITLE
Width / height of SVG not taken into account

### ISSUE THREAD

**Issue by jbransen** [diagrams/diagrams-input#12]
When reading in an SVG with `loadImageEmbedded` the width and height of the SVG seem to be ignored. When reading an SVG and then asking the diagrams library for the width and height, the reported numbers seem to be the bounding box of the objects in the SVG, not the size of the full image. Is this a bug or is this on purpose?

On a related note, after upgrading to GHC 8 my diagrams look a bit different, and I *think* that it is related to the width/height of the svg components being reported differently, but I am not 100% sure.

**Comment by jbransen** [comment]
See https://gist.github.com/jbransen/d5200196b3d272629a98891a98fb379d for an example of what is going wrong. When I compile Example.hs on my machine (GHC 8.0.1, diagrams-lib 1.4.0.1, diagrams-svg 1.4.1) and run ./Example -o output.svg, it outputs

```
Background = (100.00000000000003,50.0)
Foreground = (60.000000000000014,30.000000000000004)
```
and produces output.svg that is also attached. I see two problems here, which may be related:
- The reported height for foreground makes no sense. The SVG image size is 100x50, and the ellipse itself is 60x40. The 60 for width makes some sense, but I have no clue where the 30 for height could come from.
- The output is wrong, as the ellipse is scaled down. Om the gist page you can clearly see that the ellipse should be much bigger. Note that this should be a quite trivial example, just putting two images of the same size on top of each other.

**Comment by tkvogt** [comment]
It's a feature not implemented yet. See Todo on main page "Scale viewbox to width and height". I think I hesitated because some things are not clear to me. Generally there should be the same behaviour as in http://projects.haskell.org/diagrams/doc/manual.html#images
 - Does that mean to use local or global coordinates?
 - When the width and height don't match the underlying viewbox, there has to be a scheme how to place the image (svg has extra attributes for this: https://www.w3.org/TR/SVG/coords.html#PreserveAspectRatioAttribute). Diagrams does not have this. But it should! Who wants to add this to digrams? Until then you unfortunately have to scale the images yourself.

**Comment by jbransen** [comment]
No, I don't think this is related to viewbox scaling. Have you taken a close look at my example? For those SVG images the viewbox matches width/height nicely, so no scaling needs to be done, but there is some unexpected scaling going on!

We have:
- A red ellipse of 60x40
- Diagrams reports it is 60x30  (why? did its aspect ratio change ?!)
- It it outputted as 37x25  (why? I didn't say resize anywhere)

The background (the other image) has the exact same viewbox and width/height but it is not resized. The difference between local or global coordinates should not matter here. What I don't understand is that this should be a trivial example, just putting two images of the same size on top of each other, but it doesn't work anymore. No resizing should happen here, and no strange viewboxes either.

I guess my real question is: how to put background.svg and foreground.svg on top of each other without resizing? This was working before on my machine (around the time of commit 368b8d3 ) but since then I've upgraded GHC and some packages, and now it is broken. It is quite obvious that this is not due to a change in diagrams-input (nothing really changed), but it is related as strange things happen to the sizes of SVG elements.

**Comment by tkvogt** [comment]
Yes, this is a bug. I am currently narrowing it down. There must be something wrong with diagrams-input, because the following produces correct output:

let fg1 = unitCircle # scaleX 30 # scaleY 20 # translate (r2 (50, 25))
mainWith $ fg1 # center `atop` bg # center

**Comment by tkvogt** [comment]
It works now for your example. It should also generally work. The mistake was using width and height of the diagram instead of the width and height attribute in the <svg> tag. It now scales acording to these attributes. The aspect ratio is kept by centering the image when the viewbox has a different ratio than the width and height attribute in the <svg> tag.
